---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anodiam-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anodiam-ui
  template:
    metadata:
      labels:
        app: anodiam-ui
    spec:
      containers:
        - name: anodiam-ui
          image: APP_IMAGE
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html/config.js
              name: config-js
              subPath: config.js
      volumes:
        - configMap:
            name: anodiam-ui-config
          name: config-js