---
apiVersion: v1
kind: Service
metadata:
  name: anodiam-ui
spec:
  type: ClusterIP
  selector:
    app: anodiam-ui
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
